      - name: Verify version.json
        if: ${{ steps.node_project.outputs.exists == 'true' }}
        run: |
          node scripts/update-version-json.mjs
          if ! git diff --exit-code version.json; then
            echo "version.json is not up-to-date. Please run 'npm install' and commit the changes."
            exit 1
          fi
